name: baterfly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  video_player: ^2.10.0
  flutter_animate: ^4.5.2
  lucide_flutter: ^0.552.0
  get: ^4.7.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/.env
    - assets/images/image_1.jpg
    - assets/images/image_2.jpg
    - assets/images/image_3.jpg
    - assets/images/image_4.jpg
    - assets/video/video_1.mp4
    - assets/video/video_2.mp4
    - assets/video/video_3.mp4
    - assets/video/video_4.mp4

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700